@startuml

!include style/activity.plantuml
' Example by Preston Lee

title Example Activity Diagram\nRendered %date('yyyy.MM.dd')


(*) --> ["New Diagram assigned"] "Create Diagram File"
note right: Create one from scratch, or use a template.
--> [Figure out corretn content] "Edit File"
note right: This is just another note
--> === BStart ===

=== BStart === --> "Get Work Done"
if "You're done?" then
    --> [yes] "Go To Sleep"
    --> === BEnd ===

else
    -> [no] "Take a Break"
    --> === BEnd ===
endif

=== BStart === --> "Turn off Distractions"
--> === BEnd ===

--> "Commit and Push File"
--> [Automated CI/CD] "Check out Deployment!" 
--> (*)

@enduml
